---
title: "diet study plots"
author: "Dani Blumstein"
date: "1/18/2022"
output: html_document
---
#final diet paper graphs
#interval plots
######################################################################################
```{r}
ylim <- max(auc_data$mgH2O)-3000
mgh2o<-ggplot(auc_data, aes(x = diet, y = mgH2O, color= diet)) +
  geom_violin(size = .75) +
  geom_jitter(alpha = .5) +
  stat_compare_means(aes(group=diet), label = "p.signif", method="t.test", label.y = ylim)+
  facet_grid(rows = vars(sex), cols = vars(interval)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),legend.position = "none")+
  scale_color_manual(values=c("#0571B0", "grey31", "blue"))+
  scale_x_discrete(labels = c("standard diet", "low fat diet"))
save("mgh2o", 15, 10, mgh2o)

ylim <- max(auc_data$EE)-2000
EE <- ggplot(auc_data, aes(x = diet, y = EE, color= diet)) +
  geom_violin(size = .75) +
  geom_jitter(alpha = .5) +
  stat_compare_means(aes(group=diet), label = "p.signif", method="t.test", label.y = ylim)+
  facet_grid(rows = vars(sex), cols = vars(interval)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),legend.position = "none")+
  scale_color_manual(values=c("#0571B0", "grey31", "blue"))+
  scale_x_discrete(labels = c("standard diet", "low fat diet"))
save("EE", 15, 10, EE)

ylim <- max(auc_data$RQ)-10000
RQ <- ggplot(auc_data, aes(x = diet, y = RQ, color= diet)) +
  geom_violin(size = .75) +
  geom_jitter(alpha = .5) +
  stat_compare_means(aes(group=diet), label = "p.signif", method="t.test", label.y = ylim)+
  facet_grid(rows = vars(sex), cols = vars(interval)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),legend.position = "none")+
  scale_color_manual(values=c("#0571B0", "grey31", "blue"))+
  scale_x_discrete(labels = c("standard diet", "low fat diet"))
save("RQ", 15, 10, RQ)
```

#elecros
######################################################################################
```{r}
electrolyte_data_diet_select <- electrolyte_data_diet[,c("experiment","sex","weight","mouse_ID", "Na", "K", "Crea", "BUN", "Hct", "iCa")]
plist_electro <- list()

all_electro_T <- melt(electrolyte_data_diet_select, id.vars = c("experiment","sex", "weight", "mouse_ID"), variable.name = "electro")

all_electro_s <- subset(all_electro_T, all_electro_T$electro == "Na")
ylim <- max(all_electro_s$value, na.rm = TRUE)
plist_electro[["Na"]] <-all_electro_s %>%
  ggplot(aes(x="Na", y=value, fill=experiment),na.rm = FALSE) +
  geom_violin(width=1, size=0.5, alpha = 0.8) +
  stat_compare_means(aes(group=experiment), label = "p.signif", method="t.test",na.rm = FALSE, label.y = ylim+.1)+
  scale_fill_manual(values=c( "grey31", "#0571B0", "#CA0020"))+
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme( plot.title = element_text(face = "bold", size = (15),family = "Helvetica",hjust = 0.5),axis.text.x=element_blank()) +
  xlab("")+
  ylab("")+
  labs(title= "Na")+
  expand_limits(y=c(NA, ylim+2))+
  facet_wrap(~sex)
save("Na", 13,10, plist_electro[["Na"]])

all_electro_s <- subset(all_electro_T, all_electro_T$electro == "K")
ylim <- max(all_electro_s$value, na.rm = TRUE)
plist_electro[["K"]] <-all_electro_s %>%
  ggplot(aes(x="K", y=value, fill=experiment),na.rm = FALSE) +
  geom_violin(width=1, size=0.5, alpha = 0.8) +
  stat_compare_means(aes(group=experiment), label = "p.signif", method="t.test",na.rm = FALSE, label.y = ylim+1)+
  scale_fill_manual(values=c( "grey31", "#0571B0", "#CA0020"))+
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(legend.position = "none", plot.title = element_text(face = "bold", size = (15),family = "Helvetica",hjust = 0.5),axis.text.x=element_blank()) +
  xlab("")+
  ylab("")+
  labs(title= "K")+
  expand_limits(y=c(NA, ylim+2))+
  facet_wrap(~sex)
save("K", 13,10, plist_electro[["K"]])


all_electro_s <- subset(all_electro_T, all_electro_T$electro == "Crea")
ylim <- max(all_electro_s$value, na.rm = TRUE)
plist_electro[["Crea"]] <-all_electro_s %>%
  ggplot(aes(x="Crea", y=value, fill=experiment),na.rm = FALSE) +
  geom_violin(width=1, size=0.5, alpha = 0.8) +
  stat_compare_means(aes(group=experiment), label = "p.signif", method="t.test",na.rm = FALSE, label.y = ylim+.006)+
  scale_fill_manual(values=c( "grey31", "#0571B0", "#CA0020"))+
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(legend.position = "none", plot.title = element_text(face = "bold", size = (15),family = "Helvetica",hjust = 0.5),axis.text.x=element_blank()) +
  xlab("")+
  ylab("")+
  scale_y_continuous(labels = scales::number_format(accuracy = 0.01))+
  labs(title= "Crea")+
  expand_limits(y=c(NA, ylim+.008))+
  facet_wrap(~sex)
save("Crea", 13,10, plist_electro[["Crea"]])

all_electro_s <- subset(all_electro_T, all_electro_T$electro == "BUN")
ylim <- max(all_electro_s$value, na.rm = TRUE)
plist_electro[["BUN"]] <-all_electro_s %>%
  ggplot(aes(x="BUN", y=value, fill=experiment),na.rm = FALSE) +
  geom_violin(width=1, size=0.5, alpha = 0.8) +
  stat_compare_means(aes(group=experiment), label = "p.signif", method="t.test",na.rm = FALSE, label.y = ylim)+
  scale_fill_manual(values=c( "grey31", "#0571B0", "#CA0020"))+
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(legend.position = "none", plot.title = element_text(face = "bold", size = (15),family = "Helvetica",hjust = 0.5),axis.text.x=element_blank()) +
  xlab("")+
  ylab("")+
  labs(title= "BUN")+
  expand_limits(y=c(NA, ylim+2.5))+
  facet_wrap(~sex)
save("BUN", 13,10, plist_electro[["BUN"]])

all_electro_s <- subset(all_electro_T, all_electro_T$electro == "Hct")
ylim <- max(all_electro_s$value, na.rm = TRUE)
plist_electro[["Hct"]] <-all_electro_s %>%
  ggplot(aes(x="Hct", y=value, fill=experiment),na.rm = FALSE) +
  geom_violin(width=1, size=0.5, alpha = 0.8) +
  stat_compare_means(aes(group=experiment), label = "p.signif", method="t.test",na.rm = FALSE, label.y = ylim)+
  scale_fill_manual(values=c( "grey31", "#0571B0", "#CA0020"))+
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(legend.position = "none", plot.title = element_text(face = "bold", size = (15),family = "Helvetica",hjust = 0.5),axis.text.x=element_blank()) +
  labs(title= "Hct")+
  xlab("")+
  ylab("")+
  expand_limits(y=c(NA, ylim+2.7))+
  facet_wrap(~sex)
save("Hct", 13,10, plist_electro[["Hct"]])

all_electro_s <- subset(all_electro_T, all_electro_T$electro == "iCa")
ylim <- max(all_electro_s$value, na.rm = TRUE)
plist_electro[["iCa"]] <-all_electro_s %>%
  ggplot(aes(x="iCa", y=value, fill=experiment),na.rm = FALSE) +
  geom_violin(width=1, size=0.5, alpha = 0.8) +
  stat_compare_means(aes(group=experiment), label = "p.signif", method="t.test",na.rm = FALSE, label.y = ylim+.1)+
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(plot.title = element_text(face = "bold", size = (15),family = "Helvetica",hjust = 0.5),axis.text.x=element_blank(),legend.position="bottom") +
  scale_fill_manual(values=c( "grey31", "#0571B0", "#CA0020", labels = c("standard diet", "low fat diet")))+
  labs(title= "iCa")+
  xlab("")+
  ylab("")+
  expand_limits(y=c(NA, ylim+.2))+
  facet_wrap(~sex)
save("iCa", 13,10, plist_electro[["iCa"]])

electo_plots <- gridExtra::grid.arrange(grobs = plist_electro)
save("electo_plots", 15,15, electo_plots)
```

#temp plot
######################################################################################
```{r}
metric0 <- "Deg_C"
target <- 7
#the "cages20april" is what you will need to change to look at whatever temperature you are interest in
cagetemp <- cages18sep %>% filter(animal %in% target)
cagetemp <- tail(cagetemp, n=320)
measurement_zero1 <- cagetemp %>%  dplyr::select(all_of(metric0))
df<-as.data.frame(measurement_zero1[[metric0]])
measurement_zero2 <- cagetemp %>%  dplyr::select(all_of("H2O_WVP"))
df<-as.data.frame(measurement_zero2[["H2O_WVP"]])

cagetemp$seconds <- as.numeric(cagetemp$StartTime)

temp <- ggplot(data = cagetemp,aes(x=seconds)) +
  geom_rect(data = cages, aes(xmin = 0 , xmax = 21600, ymin = -Inf, ymax = Inf, alpha = 0.4), fill = "grey", color = "grey")+
  geom_rect(data = cages, aes(xmin = 72000 , xmax = 86400, ymin = -Inf, ymax = Inf,alpha = 0.4),fill = "grey", color = "grey")+
  geom_line(aes(y =measurement_zero1[[metric0]], color= "darkorchid")) +
  labs(x = "", y = "degrees celsius") +
  theme(axis.title = element_text(size = 15))+
  scale_x_continuous(expand = c(0, 0))+
  theme_classic()+
  theme(legend.position = "none")

save("temp", 15, 5, temp)
```

#diet multiplot
######################################################################################
```{r}
cages_diet <- cages[,c("Sex","EE","H2Omg", "RQ", "Deg_C", "weight", "experiment", "StartTime", "FQ")]

col_names <- names(cages_diet)
col_names <- col_names[2:4]

plot_list <- list()

for (i in col_names){
  if (i=="RQ")
  {
    plot <- ggplot(cages_diet, aes_string(x=cages_diet$StartTime, y=i, color=as.factor(cages_diet$experiment))) +
      geom_rect(data = cages, aes(xmin = 0 , xmax = 21600, ymin = -Inf, ymax = Inf, alpha = 0.4), fill = "grey", color = "grey")+
      geom_rect(data = cages, aes(xmin = 72000 , xmax = 86400, ymin = -Inf, ymax = Inf,alpha = 0.4),fill = "grey", color = "grey")+
      geom_point(aes(alpha=0.3,group=as.factor(experiment), color=as.factor(experiment)), size = 1)+
      geom_smooth(data=df$V1, method='loess', span=.1, level=0.99)+
      labs(x = "seconds", y = i)+
      #scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M")+
      theme_classic()+
      #geom_hline(aes(yintercept=FQ))+
      ylim(0.5, 2)+
      guides(alpha = FALSE)+
      scale_color_manual(values=c("#0571B0", "grey31", "blue"),name = "", labels = c("standard diet", "low fat diet"))+
      theme(legend.position="bottom", axis.text.x=element_blank())+
      scale_x_continuous(expand = c(0, 0))+
      facet_grid(cols = vars(Sex))
    plot_list[[i]] <- plot
  }
  else
  {
    plot <- ggplot(cages_diet, aes_string(x=cages_diet$StartTime, y=i, color=as.factor(cages_diet$experiment))) +
      geom_rect(data = cages, aes(xmin = 0 , xmax = 21600, ymin = -Inf, ymax = Inf, alpha = 0.4), fill = "grey", color = "grey")+
      geom_rect(data = cages, aes(xmin = 72000 , xmax = 86400, ymin = -Inf, ymax = Inf,alpha = 0.4),fill = "grey", color = "grey")+
      geom_point(aes(alpha=0.3,group=as.factor(experiment), color=as.factor(experiment)), size = 1)+
      geom_smooth(data=df$V1, method='loess', span=.1, level=0.99)+
      labs(x = "", y = i)+
      #scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:%M")+
      theme_classic()+
      guides(alpha = FALSE)+
      scale_color_manual(values=c("#0571B0", "grey31", "blue"))+
      theme(legend.position = "none", axis.text.x=element_blank())+
      scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))+
      facet_grid(cols = vars(Sex))
    plot_list[[i]] <- plot
  }
}
```

```{r}
remotes::install_github("coolbutuseless/ggpattern")
library(ggpattern)

p1 <- ggplot(auc_data, aes(x=interval, y=RQ, fill = trt))+
  geom_boxplot()+
  scale_fill_manual(values=c("#0571B0", "grey31", "#0571B0", "grey31"),name = "treatment", labels = c("standard diet", "low fat diet"))+
  geom_boxplot_pattern(aes(pattern = sex), pattern_spacing = 0.05) +
  labs(y = "AUC of RQ")+
  geom_signif(
    #y_position = c(5.3, 8.3), xmin = c(0.8, 1.8), xmax = c(1.2, 2.2),
    annotation = c("**", "NS"), tip_length = 0) +
  geom_signif(comparisons = list(c("S1", "S2")), y_position = 9.3, tip_length = 0, vjust = 0.2) +
  theme(legend.position = "none")

p2<-ggplot(auc_data, aes(x=interval, y=EE, fill = trt))+
  geom_boxplot()+
  scale_fill_manual(values=c("#0571B0", "grey31", "#0571B0", "grey31"),name = "treatment", labels = c("standard diet", "low fat diet"))+
  geom_boxplot_pattern(aes(pattern = sex), pattern_spacing = 0.05) +
  labs(y = "AUC of EE")+
  theme(legend.position = "none")

p3<-ggplot(auc_data, aes(x=interval, y=mgH2O, fill = trt))+
  geom_boxplot()+
  scale_fill_manual(values=c("#0571B0", "grey31", "#0571B0", "grey31"),name = "treatment", labels = c("standard diet", "low fat diet"))+
  geom_boxplot_pattern(aes(pattern = sex), pattern_spacing = 0.05) +
  labs(y = "AUC of RWL")+
  theme(legend.position = "none")


p2|p3|p1

save("auc", 35, 15, p3|p2|p1)
save("auc_legond", 15, 25, p4)

RQ/H2Omg/EE
delta_temp/body_temp
delta_weight/weight
```